{% set name = "loopdesigner" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/gabriele-vajente/loopdesigner/-/archive/{{ version }}/loopdesigner-{{ version }}.tar.gz
  sha256: dfad4453beca4e4d9bfe3c27332d7727422b55f87f0eb764ee2a377f3ec27a7a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - python-foton
    - pyqtgraph
    - pyqt
    - gpstime
    - gwpy

test:
  imports:
    - loopdesigner

about:
  home: https://git.ligo.org/gabriele-vajente/loopdesigner
  summary: 'Graphical user interface to design and tune single-input single-output feedback control loops'
  description:
    Graphical user interface to design and tune single-input single-output feedback control loops.
    Loosely inspired by MATLAB sisotool
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://git.ligo.org/gabriele-vajente/loopdesigner
  doc_url: https://git.ligo.org/gabriele-vajente/loopdesigner/-/blob/main/loopdesigner/TUTORIAL.md

extra:
  recipe-maintainers:
    - gabrielevajente
