{% set name = "loopdesigner" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/gabriele-vajente/loopdesigner/-/archive/{{ version }}/loopdesigner-{{ version }}.tar.gz
  sha256: 13d176db6b1cb9ef9937803ce0dc80afc4392c2bcda7a8bd88823cd29fcb193b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy >=1.11.0
    - python-foton
    - pyqtgraph
    - pyqt
    - gpstime
    - gwpy

test:
  imports:
    - loopdesigner

about:
  home: https://git.ligo.org/gabriele-vajente/loopdesigner
  summary: 'Graphical user interface to design and tune single-input single-output feedback control loops'
  description: Graphical user interface to design and tune single-input single-output feedback control loops. Loosely inspired by MATLAB sisotool
  license: GPL-3.0-or-later
  license_file: LICENSE
  dev_url: https://git.ligo.org/gabriele-vajente/loopdesigner
  doc_url: https://git.ligo.org/gabriele-vajente/loopdesigner/-/blob/main/loopdesigner/TUTORIAL.md

extra:
  recipe-maintainers:
    - gabrielevajente
